export default {
  tableId: 'deploymentTable',
  stateSave: false,
  columns: [
    { data: 'DT_RowIndex', searchable: false, orderable: false },
    { data: 'serial_action', name: 'serial_action' },
    { data: 'bast_number', name: 'bast_number' },
    { data: 'ritm_number', name: 'ritm_number' },
    { data: 'staging_monitor', name: 'staging_monitor' },
    { data: 'holder_name', name: 'holder_name' },
    { data: 'service_label', name: 'service_label' },
    { data: 'brand', name: 'brand' },
    { data: 'model', name: 'model' },
    { data: 'category', name: 'category' },
    { data: 'company_name', name: 'company_name' },
    { data: 'company_location', name: 'company_location' },
    {
      data: 'request_category_label',
      name: 'request_category_label',
    },
    { data: 'terminated_serial', name: 'terminated_serial' },
    { data: 'status_badge', name: 'status' },
    { data: 'sla', name: 'sla' },
    { data: 'bast_date', name: 'bast_date' },
    { data: 'end_contract', name: 'end_contract' },
    { data: 'end_grace_period', name: 'end_grace_period' },
    { data: 'approved_by', name: 'approved_by' },
    // { data: 'deployment_date', name: 'deployment_date' },
    // { data: 'service_period_years', name: 'service_period_years' },
    // { data: 'service_period_months', name: 'service_period_months' },
    { data: 'action', name: 'action', orderable: false, searchable: false },
  ],
  filterFields: ['serial', 'brand', 'model', 'unit_status', 'service_code'],
  formId: 'filter-staging',
  resetButtonId: 'reset-staging-filter',
  liveSearch: false,
  order: [14, 'asc'],
};
