<x-data-table :id="'stagingTable'"
	:columns="[
	    'Ticket Ref',
	    'Customer Ref',
	    'Title',
	    'Caller',
	    'Assigned Team',
	    'Holder Organization',
	    'Assigned To',
	    'Location',
	    'Customer Contact',
	    'Customer',
	    'Status',
	    'Request Type',
	    'Start Date',
	    'End Date',
	    'Last Update',
	    'Closed At',
	    'Description',
	    'Urgency',
	    'Impact',
	    'Priority',
	    'Service',
	    'Service Subcategory',
	    // 'Action',
	]">
</x-data-table>
